name: 🚀 publish

on:
  push:
    branches:
      - main

jobs:
  build_image:
    permissions: write-all
    name: release image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      
      - name: Gather details
        id: details
        run: |
          echo image=$(make image) >> $GITHUB_OUTPUT
          echo version=$(make version) >> $GITHUB_OUTPUT
          echo pversion=$(make pversion) >> $GITHUB_OUTPUT
      
      - name: Build and push image - release
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: ${{ steps.details.outputs.image }}:latest-build-cache
          cache-to: ${{ steps.details.outputs.image }}:latest-build-cache
          tags: |
            ${{ steps.details.outputs.image }}:${{ steps.details.outputs.version }}
            ${{ steps.details.outputs.image }}:${{ steps.details.outputs.pversion }}
            ${{ steps.details.outputs.image }}:latest

      - name: Show summary
        run: |
          echo 'Published:  ' >> ${GITHUB_STEP_SUMMARY}
          echo '* `${{ steps.details.outputs.image }}:${{ steps.details.outputs.pversion }}`' >> ${GITHUB_STEP_SUMMARY}
          echo '* `${{ steps.details.outputs.image }}:${{ steps.details.outputs.version }}`' >> ${GITHUB_STEP_SUMMARY}
          echo '* `${{ steps.details.outputs.image }}:latest`' >> ${GITHUB_STEP_SUMMARY}
